#################################
#    Drive Configuration File   #
#   Change the mount and name!  #
#################################
[drives]
targetNames = ["Root", "Home"]
targetMounts = ["/", "/home"]